### ISSUE TITLE
申请权限

### ISSUE THREAD

**Issue by Ronadlo7** [zhaolongs/flutter-ho#1]
1.权限申请的逻辑有一点不对，第一个弹窗是自定义的，点击同意，权限状态还是属于第一次申请，然后又会走到if (status.isUndetermined) {
      //第一次申请
      showPermissonAlert(widget.permissionList[0], "同意", permission);
    }
所以会一直弹出第一个同意的弹窗
2.弹窗消失后页面就卡住了，点击任何位置都没反应

**Comment by zhaolongs** [comment]
新版本 master 已处理
